import { useState } from 'react';
import { useNotifications } from './useNotifications';

export function NotificationsPopover() {
  const [isOpen, setOpen] = useState(false); const notifications = useNotifications();
  const open = () => { setOpen(true); void notifications.load(notifications.readFilter, 1); };
  const totalPages = Math.max(1, Math.ceil(notifications.total / notifications.pageSize));
  return <div className="notifications-control"><button type="button" className="notification-bell" aria-label={`Thông báo${notifications.unreadTotal ? ` (${notifications.unreadTotal} chưa đọc)` : ''}`} aria-expanded={isOpen} onClick={isOpen ? () => setOpen(false) : open}>🔔{notifications.unreadTotal > 0 && <span>{notifications.unreadTotal}</span>}</button>{isOpen && <><button className="notifications-scrim" type="button" aria-label="Đóng thông báo" onClick={() => setOpen(false)} /><section className="notifications-popover" role="dialog" aria-label="Thông báo"><header><h2>Thông báo</h2><label> <span className="sr-only">Lọc thông báo</span><select aria-label="Lọc thông báo" value={String(notifications.readFilter)} onChange={(event) => { void notifications.selectReadFilter(event.target.value === 'true'); }}><option value="false">Chưa đọc</option><option value="true">Đã đọc</option></select></label><button type="button" aria-label="Đóng thông báo" onClick={() => setOpen(false)}>×</button></header>{notifications.isLoading ? <p aria-live="polite">Đang tải thông báo...</p> : notifications.error ? <p className="form-error" role="alert">{notifications.error}</p> : notifications.items.length === 0 ? <p className="empty-state">Không có thông báo {notifications.readFilter ? 'đã đọc' : 'chưa đọc'}.</p> : <div className="notification-list">{notifications.items.map((notification) => <button type="button" key={notification.id} className="notification-item" aria-label={`${notification.title} — ${notification.read ? 'Đánh dấu chưa đọc' : 'Đánh dấu đã đọc'}`} onClick={() => void notifications.setRead(notification, notifications.readFilter, notifications.page)}><strong>{notification.title}</strong><span>{notification.message}</span><small>{new Date(notification.createdAt).toLocaleString('vi-VN')}</small></button>)}</div>}<footer className="notification-pagination"><button type="button" disabled={notifications.page <= 1} onClick={() => void notifications.load(notifications.readFilter, notifications.page - 1)}>Trang trước</button><span>Trang {notifications.page}/{totalPages}</span><button type="button" disabled={notifications.page >= totalPages} onClick={() => void notifications.load(notifications.readFilter, notifications.page + 1)}>Trang sau</button></footer></section></>}</div>;
}
